name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clones our current repo
      - uses: actions/setup-node@v4
        with: 
          node-version: 18
      - run: node -v
